Repository aws/sagemaker-python-sdk, pull requests merged in 2020-10, with the labels that each got.

#1940 doc: fix broken link to moved notebook
  doc/overview.rst
Labels: type: bug, type: documentation

#1943 feat: add network isolation support for PipelineModel
  src/sagemaker/pipeline.py
  tests/unit/test_pipeline_model.py
Labels: type: enhancement

#1949 fix: add missing scikit-learn account IDs for af-south-1 and eu-south-1
  src/sagemaker/image_uri_config/sklearn.json
Labels: related: scikit-learn, type: bug

#1974 doc: clarify non-breaking changes after v1 forward port
  doc/v2.rst
Labels: priority: high, type: documentation
