Repository aws/sagemaker-python-sdk, pull requests merged in 2022-04, with the labels that each got.

#3027 feature: Hugging Face Transformers 4.17 for TF 2.6
  src/sagemaker/image_uri_config/huggingface.json
  tests/conftest.py
Labels: needs contributor changes

#3043 fix: Add back the Fix for Pipeline variables related customer issues
  src/sagemaker/estimator.py
  src/sagemaker/model.py
  src/sagemaker/parameter.py
  src/sagemaker/processing.py
  src/sagemaker/session.py
  src/sagemaker/tensorflow/model.py
  src/sagemaker/tuner.py
  src/sagemaker/workflow/__init__.py
  src/sagemaker/workflow/_repack_model.py
  src/sagemaker/workflow/_utils.py
  src/sagemaker/workflow/airflow.py
  src/sagemaker/workflow/clarify_check_step.py
  src/sagemaker/workflow/condition_step.py
  src/sagemaker/workflow/conditions.py
  src/sagemaker/workflow/pipeline.py
  src/sagemaker/workflow/quality_check_step.py
  tests/integ/sagemaker/workflow/test_model_registration.py
  tests/integ/sagemaker/workflow/test_training_steps.py
  tests/integ/sagemaker/workflow/test_tuning_steps.py
  tests/integ/sagemaker/workflow/test_workflow.py
  tests/integ/sagemaker/workflow/test_workflow_with_clarify.py
  tests/unit/sagemaker/workflow/test_repack_model_script.py
  tests/unit/sagemaker/workflow/test_step_collections.py
  tests/unit/sagemaker/workflow/test_steps.py
  tests/unit/sagemaker/workflow/test_utils.py
Labels: component: pipelines

#2721 fix: retry context delete
  tests/integ/sagemaker/lineage/conftest.py
Labels: needs contributor changes

#3068 feature: Add Jumpstart example notebooks
  doc/doc_utils/jumpstart_doc_utils.py
  doc/overview.rst
Labels: type: documentation

#3072 doc: sm model parallel 1.8.0 release notes
  doc/api/training/distributed.rst
  doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
  doc/api/training/smp_versions/latest.rst
Labels: type: documentation

#3040 Implement subclass compatibility for workflow pipeline job steps
  src/sagemaker/amazon/amazon_estimator.py
  src/sagemaker/clarify.py
  src/sagemaker/estimator.py
  src/sagemaker/processing.py
  src/sagemaker/session.py
  src/sagemaker/spark/processing.py
  src/sagemaker/transformer.py
  src/sagemaker/tuner.py
  src/sagemaker/workflow/pipeline_context.py
  src/sagemaker/workflow/steps.py
  src/sagemaker/workflow/utilities.py
  tests/unit/sagemaker/workflow/test_pipeline_session.py
  tests/unit/sagemaker/workflow/test_processing_step.py
  tests/unit/sagemaker/workflow/test_steps.py
  tests/unit/sagemaker/workflow/test_training_step.py
  tests/unit/sagemaker/workflow/test_transform_step.py
  tests/unit/sagemaker/workflow/test_tuning_step.py
Labels: component: pipelines
