Repository aws/sagemaker-python-sdk, pull requests merged in 2022-03, with the labels that each got.

#2861 feature: TensorFlow 2.4 for Neo
  src/sagemaker/image_uri_config/neo-tensorflow.json
Labels: needs contributor changes

#2950 fix: Remove sagemaker_job_name from hyperparameters in TrainingStep
  src/sagemaker/workflow/steps.py
  tests/unit/sagemaker/workflow/test_step_collections.py
  tests/unit/sagemaker/workflow/test_steps.py
Labels: type: question

#2968 documentation: smddp doc update
  doc/api/training/sdp_versions/latest/smd_data_parallel_tensorflow.rst
Labels: type: documentation

#2969 documentation: update sagemaker training compiler docstring
  src/sagemaker/huggingface/estimator.py
  src/sagemaker/training_compiler/config.py
Labels: type: documentation

#2976 feature: Inferentia Neuron support for HuggingFace
  src/sagemaker/huggingface/model.py
  src/sagemaker/image_uri_config/huggingface-neuron.json
  src/sagemaker/image_uris.py
  tests/conftest.py
  tests/unit/sagemaker/huggingface/test_estimator.py
Labels: HuggingFace

#2958 feature: Add support for TF2.7
  src/sagemaker/fw_utils.py
  src/sagemaker/image_uri_config/tensorflow.json
  tests/integ/test_tf.py
  tests/unit/test_fw_utils.py
Labels: needs contributor changes

#2996 documentation: minor fixes for smddp 1.4.0 doc
  doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst
Labels: type: documentation
