Repository aws/sagemaker-python-sdk, pull requests merged in 2023-12, with the labels that each got.

#4281 fix: fast follow on js uncompressed support - ModelBuilder
  src/sagemaker/serve/model_server/tgi/prepare.py
Labels: bug

#4299 fix: update image and hardware validation with inf and graviton
  src/sagemaker/serve/utils/types.py
  src/sagemaker/serve/validations/check_image_and_hardware_type.py
  tests/unit/sagemaker/serve/validations/test_check_image_and_hardware_type.py
Labels: ModelBuilder

#4305 feature: support model.register() with triton model
  src/sagemaker/serve/marshalling/triton_translator.py
  src/sagemaker/serve/model_server/triton/triton_builder.py
  tests/unit/sagemaker/serve/model_server/triton/test_triton_builder.py
Labels: ModelBuilder

#4298 fix: mitigation of xgboost container incompatibility with new version
  src/sagemaker/serve/builder/model_builder.py
  src/sagemaker/serve/detector/dependency_manager.py
  src/sagemaker/serve/model_server/torchserve/prepare.py
  src/sagemaker/serve/model_server/torchserve/xgboost_inference.py
  tests/unit/sagemaker/serve/builder/test_model_builder.py
  tests/unit/sagemaker/serve/detector/test_dependency_manager.py
  tests/unit/sagemaker/serve/model_server/torchserve/test_prepare.py
Labels: bug, ModelBuilder

#4294 Fix: Updated js mb compression logic - ModelBuilder
  src/sagemaker/serve/builder/jumpstart_builder.py
  src/sagemaker/serve/builder/tgi_builder.py
  src/sagemaker/serve/model_server/djl_serving/prepare.py
  src/sagemaker/serve/model_server/tgi/prepare.py
  tests/unit/sagemaker/serve/builder/test_djl_builder.py
  tests/unit/sagemaker/serve/model_server/constants.py
  tests/unit/sagemaker/serve/model_server/djl_serving/test_djl_prepare.py
  tests/unit/sagemaker/serve/model_server/tgi/test_tgi_prepare.py
Labels: bug, ModelBuilder

#4334 Fix: Add additional model builder telemetry
  src/sagemaker/serve/utils/telemetry_logger.py
  tests/unit/sagemaker/serve/utils/test_telemetry_logger.py
Labels: bug, ModelBuilder
